env:
  node: true
  es6: true
  browser: true
parserOptions:
  sourceType: module
  ecmaVersion: 2016
  ecmaFeatures:
    jsx: true
extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - react
  - prettier
  - jsx-a11y
rules:
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      semi: false
