env:
  node: true
  es6: true
  browser: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 2016
  ecmaFeatures:
    jsx: true
extends:
  - airbnb
  - prettier
  - prettier/react
plugins:
  - react
  - prettier
  - jsx-a11y
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
      moduleDirectory:
        - node_modules
        - src
rules:
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
      semi: false
